### Contents  
1 Import libraries and datasets  
2 Inspect schools data and clean  
3 Inspect population data and clean  
4 Inspect population density data and clean  
5 Export datasets

### 1 Import libraries and datasets

In [69]:
# import libraries
import pandas as pd
import numpy as np
import os

In [70]:
# create path
path = r"C:\Users\cathe\OneDrive\Data Analysis\2 6 Schools in England and Wales\02 Data"

In [71]:
# import dataset 1: schools information and inspection results
df1 = pd.read_csv(os.path.join(path, "Original Data", "Schools_2025.csv"), encoding='utf-8', encoding_errors='ignore', index_col=False)

In [72]:
# import dataset 2: population census data
df2 = pd.read_csv(os.path.join(path, "Original Data", "Population.csv"), index_col=False)

In [73]:
# import dataset 3: population densities
df3 = pd.read_csv(os.path.join(path, "Original Data", "Densities.csv"), index_col=False)

### 2 Inspect schools data and clean

In [75]:
df1.shape

(21990, 38)

In [104]:
# Investigate quantitative columns
df1.describe()

,URN,The income deprivation affecting children index (IDACI) quintile,Total number of pupils,Quality of education,Behaviour and attitudes,Personal development,Effectiveness of leadership and management,Previous graded inspection overall effectiveness,Previous quality of education,Previous behaviour and attitudes,Previous personal development,Previous effectiveness of leadership and management
count,21901.000000,21901.000000,21901.000000,21802.000000,21802.000000,21802.000000,21802.000000,21196.000000,21196.000000,21196.000000,21196.000000,21196.000000
mean,129521.502397,3.029679,386.787864,5.238418,5.132924,5.097560,1.919824,2.233393,8.642291,8.612002,8.602236,2.138658
std,16048.386817,1.409568,365.418831,3.481080,3.576773,3.606826,0.521623,0.814599,1.423489,1.547809,1.584745,0.796118
min,100000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,115137.000000,2.000000,166.000000,2.000000,2.000000,2.000000,2.000000,2.000000,9.000000,9.000000,9.000000,2.000000
50%,136469.000000,3.000000,247.000000,3.000000,3.000000,2.000000,2.000000,2.000000,9.000000,9.000000,9.000000,2.000000
75%,143452.000000,4.000000,446.000000,9.000000,9.000000,9.000000,2.000000,3.000000,9.000000,9.000000,9.000000,3.000000
max,151631.000000,5.000000,3077.000000,9.000000,9.000000,9.000000,4.000000,4.000000,9.000000,9.000000,9.000000,4.000000

Comments:
- URN: all six digit numbers with 21990 distinct values
- IDACI: quartiles as expected; 89 missing entries
- Total number of pupils: min 0 is an error, needs investigating and removing; max is large and should be checked; 47 missing values
- Other URN columns: looks like URNs have changed, but only using them to identify distinct schools, so will delete these columns
- Overall, quality, behaviour, personal, effectiveness: see if can find rationale for numbers.  Why is max 9 for some and 4 for others?
- Overall effectiveness: check that column for latest inspection also in dataframe as has not appeared in above table.  Data type issue?

In [82]:
# Remove all rows containing missing IDACI quintile
df1.dropna(subset=["The income deprivation affecting children index (IDACI) quintile"], inplace=True)

Note: All missing values for Total number of pupils have also been removed.  Minimum value for Total number of pupils is now 1.

In [84]:
df1.shape

(21901, 38)

In [112]:
# Investigate schools with 1 pupil
no_pupils = df1[df1["Total number of pupils"] == 1]
print(no_pupils[["Total number of pupils", "Type of education"]])

       Total number of pupils                        Type of education
1671                      1.0                      Pupil Referral Unit
9617                      1.0                      Pupil Referral Unit
9974                      1.0                      Pupil Referral Unit
10238                     1.0                      Pupil Referral Unit
10244                     1.0                      Pupil Referral Unit
10346                     1.0                      Pupil Referral Unit
10369                     1.0                      Pupil Referral Unit
10414                     1.0                      Pupil Referral Unit
10557                     1.0                      Pupil Referral Unit
11936                     1.0                      Pupil Referral Unit
12392                     1.0      Free School - Alternative Provision
14644                     1.0      Free School - Alternative Provision
15707                     1.0  Academy Alternative Provision Converter
18917                     1.0      Free School - Alternative Provision
19415                     1.0  Academy Alternative Provision Converter

PRUs are often very small and alternative provision similar, so I will leave these records as they are.

In [95]:
# Investigate schools with over 2000 pupils
many_pupils = df1[df1["Total number of pupils"] > 2000]
print(many_pupils["Total number of pupils"])

95       2080.0
595      2323.0
597      2160.0
598      2900.0
839      2015.0
1237     2207.0
3135     2518.0
4277     2196.0
5341     2507.0
6123     2002.0
10502    2367.0
10597    2003.0
10674    2188.0
10727    2356.0
10845    2527.0
10870    2424.0
10933    2467.0
10957    2490.0
10992    2097.0
11058    2094.0
11090    2187.0
11144    2106.0
11146    2880.0
11211    2126.0
11220    2121.0
11264    3077.0
11275    2122.0
11321    2134.0
11401    2275.0
11420    2024.0
11442    2273.0
11476    2158.0
11519    2068.0
11537    2080.0
11780    2040.0
11796    2052.0
11944    2008.0
12022    2060.0
12151    2013.0
12162    2645.0
12319    2060.0
12558    2014.0
12695    2276.0
13079    2084.0
13440    2178.0
13501    2056.0
14025    2094.0
14114    2779.0
14190    2628.0
14249    2050.0
15057    2593.0
16938    2471.0
18928    2037.0
19592    2223.0
19877    2116.0
20821    2201.0
Name: Total number of pupils, dtype: float64

3077 is not a long way from other school sizes, so assume it is correct

In [51]:
df1.dtypes

URN                                                                               int64
Ofsted phase                                                                     object
Type of education                                                                object
School open date                                                                 object
Admissions policy                                                                object
Sixth form                                                                       object
Region                                                                           object
Local authority                                                                  object
Postcode                                                                         object
The income deprivation affecting children index (IDACI) quintile                float64
Total number of pupils                                                          float64
Inspection number of latest graded inspection                                    object
Inspection type                                                                  object
Inspection type grouping                                                         object
Event type grouping                                                              object
Inspection start date                                                            object
Publication date                                                                 object
Does the latest graded inspection relate to the URN of the current school?       object
URN at time of latest graded inspection                                         float64
School type at time of latest graded inspection                                  object
Overall effectiveness                                                            object
Category of concern                                                              object
Quality of education                                                            float64
Behaviour and attitudes                                                         float64
Personal development                                                            float64
Effectiveness of leadership and management                                      float64
Previous graded inspection number                                                object
Previous inspection start date                                                   object
Previous publication date                                                        object
Does the previous graded inspection relate to the URN of the current school?     object
URN at time of previous graded inspection                                       float64
School type at time of previous graded inspection                                object
Previous graded inspection overall effectiveness                                float64
Previous category of concern                                                     object
Previous quality of education                                                   float64
Previous behaviour and attitudes                                                float64
Previous personal development                                                   float64
Previous effectiveness of leadership and management                             float64
dtype: object

In [57]:
# Investigate why Overall effectiveness column is dtype object, when previous overall effectiveness is float64
df1["Overall effectiveness"].value_counts()

Overall effectiveness
2             16053
1              2590
3              1552
Not judged     1378
4               270
Name: count, dtype: int64

I will leave "Not judged" in the dataset, since it accounts for over 5% of the dataset and might introduce bias if I remove these schools

In [100]:
# Drop unwanted columns which reference URN
df1 = df1.drop(["Does the latest graded inspection relate to the URN of the current school?", "URN at time of latest graded inspection", "Does the previous graded inspection relate to the URN of the current school?", "URN at time of previous graded inspection"], axis=1)

In [102]:
df1.shape

(21901, 34)

In [119]:
# Consistency checks for qualitative columns (looping through all columns for simplicity)
# Retrieve all column names as a list
columns = df1.columns

# Loop through each column and print value counts
for column in columns:
    print(f"Value counts for {column}:")
    print(df1[column].value_counts(dropna=False))
    print("\n")

Value counts for URN:
URN
100000    1
141101    1
141111    1
141110    1
141109    1
         ..
119369    1
119368    1
119367    1
119366    1
151631    1
Name: count, Length: 21901, dtype: int64


Value counts for Ofsted phase:
Ofsted phase
Primary      16719
Secondary     3412
Special       1090
Nursery        379
PRU            301
Name: count, dtype: int64


Value counts for Type of education:
Type of education
Academy Converter                            7343
Community School                             5277
Academy Sponsor Led                          2654
Voluntary Aided School                       2230
Voluntary Controlled School                  1441
Foundation School                             613
Free School                                   507
Community Special School                      446
LA Nursery School                             379
Academy Special Converter                     317
Pupil Referral Unit                           149
Free School Special                           107
Academy Special Sponsor Led                    91
Academy Alternative Provision Converter        78
Foundation Special School                      77
Non-Maintained Special School                  52
University Technical College                   44
Free School - Alternative Provision            41
Academy Alternative Provision Sponsor Led      33
Studio School                                  19
City Technology College                         3
Name: count, dtype: int64


Value counts for School open date:
School open date
NaN           9433
01/09/2012     288
01/09/2016     278
01/09/2018     251
01/08/2011     246
              ...
10/09/2012       1
06/09/2007       1
02/04/1999       1
24/04/2006       1
01/08/1997       1
Name: count, Length: 403, dtype: int64


Value counts for Admissions policy:
Admissions policy
Not applicable    17612
Non-selective      3418
Unknown             707
Selective           164
Name: count, dtype: int64


Value counts for Sixth form:
Sixth form
Does not have a sixth form    17358
Has a sixth form               2665
Not applicable                 1872
Not recorded                      6
Name: count, dtype: int64


Value counts for Region:
Region
South East                  3369
North West                  3182
London                      2557
East of England             2548
West Midlands               2420
South West                  2367
Yorkshire and the Humber    2237
East Midlands               2079
North East                  1142
Name: count, dtype: int64


Value counts for Local authority:
Local authority
Lancashire          625
Kent                591
Essex               554
Hertfordshire       531
Hampshire           529
                   ...
Hartlepool           38
Bracknell Forest     37
Rutland              20
City of London        1
Isles of Scilly       1
Name: count, Length: 153, dtype: int64


Value counts for Postcode:
Postcode
LE11 4SQ    5
PO14 3BN    4
PR9 8PA     4
NE34 0QA    4
B42 2PY     4
           ..
LA1 3BT     1
PR3 0PN     1
PR3 1RB     1
BB3 0HY     1
RG2 8AF     1
Name: count, Length: 20822, dtype: int64


Value counts for The income deprivation affecting children index (IDACI) quintile:
The income deprivation affecting children index (IDACI) quintile
4.0    4472
5.0    4468
3.0    4418
2.0    4328
1.0    4215
Name: count, dtype: int64


Value counts for Total number of pupils:
Total number of pupils
210.0     143
209.0     142
208.0     129
211.0     124
207.0     117
         ...
1553.0      1
2273.0      1
2024.0      1
1164.0      1
1917.0      1
Name: count, Length: 1785, dtype: int64


Value counts for Inspection number of latest graded inspection:
Inspection number of latest graded inspection
NaN          99
10323215      1
10032501      1
10288042      1
10019859      1
             ..
ITS443909     1
10086865      1
10348159      1
ITS429207     1
10287979      1
Name: count, Length: 21803, dtype: int64


Value counts for Inspection type:
Inspection type
S5 Inspection                                                                    14306
Requires Improvement S5 Reinspection Visit 1                                      3491
Academy First Section 5                                                           1264
Requires Improvement S5 Reinspection Visit 2                                       704
Exempt School Inspection                                                           616
Maintained Academy and School Short inspection                                     561
S8 No Formal Designation Visit                                                     186
Requires Improvement S5 Reinspection Visit 3                                       119
NaN                                                                                 99
Serious Weaknesses S5 Reinspection                                                  92
Section 8 inspection of good and outstanding schools                                76
Schools into Special Measures Visit 3                                               56
Special Measures S5 ReInspection                                                    49
Schools with Serious Weaknesses Visit 1                                             48
Schools into Special Measures Visit 4                                               36
Schools into Special Measures Visit 2                                               26
Schools into Special Measures Visit 5                                               23
Special Measures Historic                                                           20
Schools with Serious Weaknesses Visit 2                                             19
Section 8 Inspection due to Parental Complaint                                      19
Notice to Improve S5 ReInspection Historic                                          17
Requires Improvement S5 Reinspection Visit 4                                        16
Requires Improvement monitoring Visit 1                                             12
Schools into Special Measures Visit 1                                               11
Pilot 2011 s8 deemed s5 Historic                                                     8
Requires Improvement monitoring Visit 2                                              6
Schools with Serious Weaknesses Visit 3                                              5
Exempt School Inspection following a complaint                                       5
Section 5 RTI Historic                                                               5
Non Exempt School Inspection following a request from provider for inspection        4
Requires Improvement monitoring Visit 3                                              1
Section 8 inspections of good and non-exempt outstanding schools                     1
Name: count, dtype: int64


Value counts for Inspection type grouping:
Inspection type grouping
S5 Inspection                                   14306
Requires Improvement S5 Reinspection Visit 1     3491
Academy First Section 5                          1264
Section 8 deemed section 5                       1101
Requires Improvement S5 Reinspection Visit 2      704
Section 8 conversion                              638
Requires Improvement S5 Reinspection Visit 3      119
NaN                                                99
Serious Weaknesses S5 Reinspection                 92
Special Measures S5 ReInspection                   49
Notice to Improve S5 ReInspection Historic         17
Requires Improvement S5 Reinspection Visit 4       16
Section 5 RTI Historic                              5
Name: count, dtype: int64


Value counts for Event type grouping:
Event type grouping
Schools - S5                     20063
Schools - S8 deemed S5            1101
Schools  Section 8 conversion      638
NaN                                 99
Name: count, dtype: int64


Value counts for Inspection start date:
Inspection start date
01/10/2024    173
24/09/2024    157
08/10/2024    113
08/05/2024    112
26/09/2023    111
             ...
10/06/2021      1
29/03/2017      1
06/02/2020      1
04/04/2022      1
09/03/2015      1
Name: count, Length: 1461, dtype: int64


Value counts for Publication date:
Publication date
21/09/2022    233
18/01/2024    131
10/11/2024    122
24/04/2024    105
NaN            99
             ...
03/03/2012      1
16/02/2016      1
15/09/2019      1
04/04/2016      1
01/12/2015      1
Name: count, Length: 2752, dtype: int64


Value counts for School type at time of latest graded inspection:
School type at time of latest graded inspection
Community School                             6831
Academy Converter                            4593
Voluntary Aided School                       2988
Academy Sponsor Led                          2401
Voluntary Controlled School                  1874
Foundation School                             860
Community Special School                      591
Free School                                   453
LA Nursery School                             379
Pupil Referral Unit                           190
Academy Special Converter                     170
NaN                                            99
Foundation Special School                      92
Academy Special Sponsor Led                    78
Free School Special                            76
Non-Maintained Special School                  53
University Technical College                   44
Academy Alternative Provision Converter        40
Free School - Alternative Provision            39
Academy Alternative Provision Sponsor Led      28
Studio School                                  19
City Technology College                         3
Name: count, dtype: int64


Value counts for Overall effectiveness:
Overall effectiveness
2             16032
1              2573
3              1550
Not judged     1378
4               269
NaN              99
Name: count, dtype: int64


Value counts for Category of concern:
Category of concern
NaN    21615
SM       182
SWK      104
Name: count, dtype: int64


Value counts for Quality of education:
Quality of education
9.0    9978
2.0    8500
3.0    1750
1.0    1380
4.0     194
NaN      99
Name: count, dtype: int64


Value counts for Behaviour and attitudes:
Behaviour and attitudes
9.0    9978
2.0    8277
1.0    2616
3.0     788
4.0     143
NaN      99
Name: count, dtype: int64


Value counts for Personal development:
Personal development
9.0    9978
2.0    8149
1.0    3028
3.0     579
NaN      99
4.0      68
Name: count, dtype: int64


Value counts for Effectiveness of leadership and management:
Effectiveness of leadership and management
2.0    16510
1.0     3650
3.0     1382
4.0      260
NaN       99
Name: count, dtype: int64


Value counts for Previous graded inspection number:
Previous graded inspection number
NaN          705
ITS411816      1
10024898       1
ITS313454      1
ITS428863      1
            ...
10237637       1
ITS442466      1
ITS426646      1
ITS405826      1
10111414       1
Name: count, Length: 21197, dtype: int64


Value counts for Previous inspection start date:
Previous inspection start date
NaN           705
27/03/2014     56
03/07/2013     54
20/03/2013     45
08/07/2014     44
             ...
23/11/2022      1
18/01/2008      1
18/05/2021      1
09/06/2021      1
19/07/2018      1
Name: count, Length: 1909, dtype: int64


Value counts for Previous publication date:
Previous publication date
NaN           705
05/03/2010    108
16/02/2011     73
22/04/2013     73
04/03/2013     63
             ...
25/08/2016      1
19/06/2010      1
19/12/2016      1
01/10/2008      1
27/05/2015      1
Name: count, Length: 3228, dtype: int64


Value counts for School type at time of previous graded inspection:
School type at time of previous graded inspection
Community School                             8877
Voluntary Aided School                       3772
Voluntary Controlled School                  2290
Academy Converter                            1796
Foundation School                            1338
Academy Sponsor Led                          1310
Community Special School                      724
NaN                                           705
LA Nursery School                             376
Pupil Referral Unit                           225
Free School                                   141
Foundation Special School                     101
Academy Special Converter                      62
Non-Maintained Special School                  56
University Technical College                   35
Academy Special Sponsor Led                    26
Free School - Alternative Provision            15
Academy Alternative Provision Converter        14
Academy Alternative Provision Sponsor Led      14
Free School Special                            12
Studio School                                   9
City Technology College                         3
Name: count, dtype: int64


Value counts for Previous graded inspection overall effectiveness:
Previous graded inspection overall effectiveness
2.0    9670
3.0    6390
1.0    3905
4.0    1231
NaN     705
Name: count, dtype: int64


Value counts for Previous category of concern:
Previous category of concern
NaN    20670
SM       836
SWK      373
NTI       22
Name: count, dtype: int64


Value counts for Previous quality of education:
Previous quality of education
9.0    19930
3.0     1020
NaN      705
4.0      131
2.0      113
1.0        2
Name: count, dtype: int64


Value counts for Previous behaviour and attitudes:
Previous behaviour and attitudes
9.0    19930
2.0      712
NaN      705
3.0      440
4.0      104
1.0       10
Name: count, dtype: int64


Value counts for Previous personal development:
Previous personal development
9.0    19930
2.0      836
NaN      705
3.0      354
4.0       51
1.0       25
Name: count, dtype: int64


Value counts for Previous effectiveness of leadership and management:
Previous effectiveness of leadership and management
2.0    10475
3.0     5270
1.0     4411
4.0     1040
NaN      705
Name: count, dtype: int64

Comments:
- Consistent naming and no unusual results for: Ofsted phase, School open date, Admissions policy, Sixth form, Local authority. 
- Type of education, Event type grouping, Category of concern, Previous category of concern - to be deleted as too granular/technical for my project
- Region: where is Wales in the list?

In [122]:
# Delete unneeded columns mentioned above
df1 = df1.drop(["Type of education", "Event type grouping", "Category of concern", "Previous category of concern"], axis=1)

In [124]:
df1.shape

(21901, 30)

### 3 Inspect population data and clean

In [127]:
df2.shape

(357, 95)

In [133]:
df2.head()

,Code,Name,Geography,All ages,0,1,2,3,4,5,...,81,82,83,84,85,86,87,88,89,90+
0,K04000001,ENGLAND AND WALES,Country,"60,854,727","600,801","641,879","638,385","661,083","672,685","681,900",...,"335,360","288,359","287,413","271,872","250,133","222,324","195,657","170,123","142,674","551,758"
1,E92000001,ENGLAND,Country,"57,690,323","573,100","611,983","608,924","629,972","640,658","648,548",...,"314,801","270,597","270,666","256,427","235,873","209,664","184,536","160,616","134,632","521,291"
2,E12000001,NORTH EAST,Region,"2,711,380","24,711","26,256","26,370","26,959","28,242","28,768",...,"15,345","13,718","13,665","12,776","11,874","10,641","8,949","8,003","6,504","23,914"
3,E06000047,County Durham,Unitary Authority,"532,182","4,410","4,736","4,805","4,964","5,084","5,199",...,"3,180","2,922","2,790","2,542","2,361","2,164","1,825","1,596","1,284","4,497"
4,E06000005,Darlington,Unitary Authority,"110,562","1,010","1,115","1,102","1,157","1,168","1,210",...,633,592,613,554,503,448,377,354,277,"1,083"

In [129]:
df2.describe()

,Code,Name,Geography,All ages,0,1,2,3,4,5,...,81,82,83,84,85,86,87,88,89,90+
count,357,357,357,357,357,357,357,357,357,357,...,357,357,357,357,357,357,357,357,357,357
unique,357,357,8,357,341,335,335,345,342,342,...,327,317,318,311,310,307,304,291,282,333
top,K04000001,ENGLAND AND WALES,Non-metropolitan District,"60,854,727","1,051","1,282","1,283","1,040","1,266","1,332",...,860,643,481,651,501,634,470,307,345,"1,153"
freq,1,1,164,1,3,2,3,3,2,2,...,3,4,4,4,3,4,3,4,4,3

Comments:
- all counts are 357 so no missing data

### 4 Inspect population density data and clean

In [137]:
df3.shape

(331, 3)

In [139]:
df3.head()

  Lower Tier Local Authorities Code Lower Tier Local Authorities  Observation
0                         E06000001                   Hartlepool        985.5
1                         E06000002                Middlesbrough       2671.2
2                         E06000003         Redcar and Cleveland        557.1
3                         E06000004             Stockton-on-Tees        959.3
4                         E06000005                   Darlington        545.9

In [141]:
df3.describe()

        Observation
count    331.000000
mean    1713.796375
std     2482.096656
min       25.500000
25%      228.700000
50%      615.100000
75%     2298.400000
max    15702.900000

Comments:
- minimum is reasonable
- maximum is 157 people per 100m by 100m square, which seems reasonable

In [143]:
# Rename observation column
df3.rename(columns = {"Observation" : "Population Density"}, inplace = True)

In [148]:
df3.sample(5)

,Lower Tier Local Authorities Code,Lower Tier Local Authorities,Population Density
276,E09000001,City of London,2975.0
39,E06000042,Milton Keynes,930.1
26,E06000027,Torbay,2215.6
242,E08000003,Manchester,4772.7
133,E07000112,Folkestone and Hythe,307.5

### 5 Export datasets

In [152]:
df1.to_csv(os.path.join(path, "Prepared Data", "schools_cleaned.csv"))

In [154]:
df2.to_csv(os.path.join(path, "Prepared Data", "population_cleaned.csv"))

In [ ]:
df3.to_csv(os.path.join(path, "Prepared Data", "densitites_cleaned.csv"))